// TrueTunes Spicetify Extension - AI-Only Voting
// Detects AI-generated music on Spotify

(function TrueTunes() {
    const GITHUB_RAW = "https://raw.githubusercontent.com/Lewdcifer666/TrueTunes/main/data/flagged.json";
    const ISSUE_URL = "https://github.com/Lewdcifer666/TrueTunes/issues/new";

    let flaggedArtists = new Map();
    let settings = {
        autoSkip: false,
        autoDislike: false,
        showWarnings: true,
        confidenceThreshold: 0.75,
        highlightInPlaylists: true
    };

    function loadSettings() {
        const saved = localStorage.getItem('truetunes_settings');
        if (saved) {
            settings = { ...settings, ...JSON.parse(saved) };
        }
    }

    function saveSettings() {
        localStorage.setItem('truetunes_settings', JSON.stringify(settings));
    }

    async function loadFlaggedList() {
        try {
            const response = await fetch(GITHUB_RAW + '?t=' + Date.now());
            const data = await response.json();

            flaggedArtists.clear();
            data.artists.forEach(artist => {
                if (artist.platforms.spotify) {
                    flaggedArtists.set(artist.platforms.spotify, artist);
                }
            });

            console.log('[TrueTunes] Loaded', flaggedArtists.size, 'flagged artists');

            if (settings.highlightInPlaylists) {
                setTimeout(highlightPlaylistItems, 1000);
            }
        } catch (error) {
            console.error('[TrueTunes] Failed to load list:', error);
        }
    }

    function checkCurrentTrack() {
        if (!Spicetify.Player.data || !Spicetify.Player.data.item) return;

        const item = Spicetify.Player.data.item;
        let artistUri = item.metadata?.reason_artist ||
            item.metadata?.artist_uri ||
            (item.artists && item.artists[0]?.uri);

        if (!artistUri) return;

        const artistId = artistUri.split(':').pop();
        const flagged = flaggedArtists.get(artistId);

        console.log('[TrueTunes] Checking artist:', artistId, flagged ? '- FLAGGED!' : '- clean');

        if (flagged && flagged.votes >= settings.confidenceThreshold) {
            handleFlaggedTrack(flagged);
        }
    }

    function handleFlaggedTrack(artist) {
        if (settings.showWarnings) {
            showNotification(artist);
        }

        if (settings.autoSkip) {
            setTimeout(() => Spicetify.Player.next(), 500);
        }

        if (settings.autoDislike) {
            dislikeTrack();
        }
    }

    function showNotification(artist) {
        Spicetify.showNotification(
            `⚠️ AI Generated Music Detected (${artist.votes} votes)`,
            false,
            5000
        );
    }

    function dislikeTrack() {
        try {
            const uri = Spicetify.Player.data.track.uri;
            Spicetify.Platform.LibraryAPI.remove({ uris: [uri] });
        } catch (error) {
            console.error('[TrueTunes] Failed to dislike:', error);
        }
    }

    function voteOnArtist(artistId, artistName = "Unknown Artist") {
        const title = `Vote: ${artistName}`;
        const body = `Platform: Spotify\nArtist ID: ${artistId}\nVote: ai\n\nAuto-generated by TrueTunes extension`;

        const url = `${ISSUE_URL}?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}&labels=vote`;

        window.open(url, '_blank');
        Spicetify.showNotification(`✓ Reported ${artistName} as AI-generated!`, false, 3000);
    }

    function injectStyles() {
        const style = document.createElement('style');
        style.textContent = `
            .truetunes-flagged-row {
                background: rgba(239, 68, 68, 0.1) !important;
                border-left: 3px solid var(--spice-text, #ef4444) !important;
            }
            
            .truetunes-badge {
                display: inline-flex;
                align-items: center;
                gap: 4px;
                padding: 2px 8px;
                border-radius: 12px;
                background: rgba(239, 68, 68, 0.2);
                color: var(--spice-text, #ef4444);
                font-size: 10px;
                font-weight: 600;
                margin-left: 8px;
                vertical-align: middle;
            }
            
            .truetunes-vote-button {
                display: inline-flex;
                margin-left: 12px;
                margin-right: 8px;
                opacity: 0;
                transition: opacity 0.2s;
            }
            
            .main-trackList-trackListRow:hover .truetunes-vote-button,
            [data-testid="tracklist-row"]:hover .truetunes-vote-button {
                opacity: 1;
            }
            
            .truetunes-vote-btn {
                min-width: 36px;
                height: 28px;
                padding: 0 10px;
                border-radius: 14px;
                border: 1px solid rgba(239, 68, 68, 0.3);
                cursor: pointer;
                display: inline-flex;
                align-items: center;
                justify-content: center;
                gap: 4px;
                font-size: 11px;
                font-weight: 700;
                transition: all 0.2s;
                background: rgba(239, 68, 68, 0.15);
                color: #ef4444;
            }
            
            .truetunes-vote-btn:hover {
                transform: scale(1.1);
                box-shadow: 0 2px 8px rgba(239, 68, 68, 0.4);
                background: rgba(239, 68, 68, 0.25);
            }
        `;
        document.head.appendChild(style);
    }

    function getArtistIdFromRow(row) {
        try {
            const artistLink = row.querySelector('a[href*="/artist/"]');
            if (artistLink) {
                const href = artistLink.getAttribute('href');
                const match = href.match(/\/artist\/([a-zA-Z0-9]+)/);
                if (match) return match[1];
            }
        } catch (e) { }
        return null;
    }

    function getArtistNameFromRow(row) {
        try {
            const artistLink = row.querySelector('a[href*="/artist/"]');
            if (artistLink) return artistLink.textContent.trim();
        } catch (e) { }
        return "Unknown Artist";
    }

    function addVoteButtonToRow(row) {
        if (row.querySelector('.truetunes-vote-button')) return;

        const artistId = getArtistIdFromRow(row);
        if (!artistId) return;

        const artistName = getArtistNameFromRow(row);
        const buttonContainer = row.querySelector('[data-testid="tracklist-row"] > div:last-child') ||
            row.querySelector('.main-trackList-rowSectionEnd');

        if (!buttonContainer) return;

        const voteButton = document.createElement('div');
        voteButton.className = 'truetunes-vote-button';
        voteButton.innerHTML = `
            <button class="truetunes-vote-btn" title="Report as AI Generated" data-artist-id="${artistId}" data-artist-name="${artistName}">
                🚨 AI
            </button>
        `;

        voteButton.querySelector('.truetunes-vote-btn').onclick = (e) => {
            e.stopPropagation();
            e.preventDefault();
            const artistId = e.currentTarget.getAttribute('data-artist-id');
            const artistName = e.currentTarget.getAttribute('data-artist-name');
            voteOnArtist(artistId, artistName);
        };

        buttonContainer.insertBefore(voteButton, buttonContainer.firstChild);
    }

    function addAIBadgeToRow(row, artist) {
        if (row.querySelector('.truetunes-badge')) return;

        const artistLink = row.querySelector('a[href*="/artist/"]');
        if (!artistLink) return;

        const badge = document.createElement('span');
        badge.className = 'truetunes-badge';
        badge.innerHTML = `⚠️ AI (${artist.votes} votes)`;
        badge.title = `This artist has been flagged as AI-generated with ${artist.votes} community votes`;

        artistLink.parentElement.appendChild(badge);
    }

    function highlightPlaylistItems() {
        if (!settings.highlightInPlaylists) return;

        const rows = document.querySelectorAll('[data-testid="tracklist-row"], .main-trackList-trackListRow');

        rows.forEach(row => {
            const artistId = getArtistIdFromRow(row);
            if (!artistId) return;

            addVoteButtonToRow(row);

            const flagged = flaggedArtists.get(artistId);
            if (flagged && flagged.votes >= 10) {
                row.classList.add('truetunes-flagged-row');
                addAIBadgeToRow(row, flagged);
            } else {
                row.classList.remove('truetunes-flagged-row');
            }
        });
    }

    function watchPlaylistChanges() {
        const observer = new MutationObserver(() => {
            highlightPlaylistItems();
        });

        observer.observe(document.body, {
            childList: true,
            subtree: true
        });

        highlightPlaylistItems();
        setInterval(highlightPlaylistItems, 3000);
    }

    async function init() {
        if (!Spicetify.Player) {
            setTimeout(init, 100);
            return;
        }

        console.log('[TrueTunes] Initializing...');

        loadSettings();
        injectStyles();
        await loadFlaggedList();

        Spicetify.Player.addEventListener('songchange', () => {
            checkCurrentTrack();
            setTimeout(highlightPlaylistItems, 500);
        });

        watchPlaylistChanges();
        setInterval(loadFlaggedList, 6 * 60 * 60 * 1000);

        console.log('[TrueTunes] Ready!');
    }

    init();

    // Context Menu Registration
    function registerContextMenu() {
        if (!Spicetify.ContextMenu || !Spicetify.React || !Spicetify.ReactDOM) {
            setTimeout(registerContextMenu, 300);
            return;
        }

        setTimeout(() => {
            try {
                new Spicetify.ContextMenu.Item(
                    "TrueTunes: Report AI Generated",
                    async ([uri]) => {
                        const artistId = uri.split(':')[2];
                        let artistName = "Unknown Artist";
                        try {
                            const item = Spicetify.Player.data?.item;
                            if (item && item.artists && item.artists[0]) {
                                artistName = item.artists[0].name;
                            }
                        } catch (e) { }

                        voteOnArtist(artistId, artistName);
                    },
                    ([uri]) => {
                        return uri.split(':')[1] === 'artist';
                    },
                    `<svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 1.5a6.5 6.5 0 100 13 6.5 6.5 0 000-13zM0 8a8 8 0 1116 0A8 8 0 010 8z"/></svg>`
                ).register();

                console.log('[TrueTunes] Context menu registered!');
            } catch (error) {
                console.error('[TrueTunes] Failed to register context menu:', error);
            }
        }, 1000);
    }

    registerContextMenu();
})();