// TrueTunes Spicetify Extension
// Detects AI-generated music on Spotify

(function TrueTunes() {
    const GITHUB_RAW = "https://raw.githubusercontent.com/Lewdcifer666/TrueTunes/main/data/flagged.json";
    const ISSUE_URL = "https://github.com/Lewdcifer666/TrueTunes/issues/new";
    
    let flaggedArtists = new Map();
    let settings = {
        autoSkip: false,
        autoDislike: false,
        showWarnings: true,
        confidenceThreshold: 0.75
    };

    // Load settings from localStorage
    function loadSettings() {
        const saved = localStorage.getItem('truetunes_settings');
        if (saved) {
            settings = { ...settings, ...JSON.parse(saved) };
        }
    }

    // Save settings to localStorage
    function saveSettings() {
        localStorage.setItem('truetunes_settings', JSON.stringify(settings));
    }

    // Load flagged artists list
    async function loadFlaggedList() {
        try {
            const response = await fetch(GITHUB_RAW + '?t=' + Date.now());
            const data = await response.json();
            
            flaggedArtists.clear();
            data.artists.forEach(artist => {
                if (artist.platforms.spotify) {
                    flaggedArtists.set(artist.platforms.spotify, artist);
                }
            });
            
            console.log('[TrueTunes] Loaded', flaggedArtists.size, 'flagged artists');
        } catch (error) {
            console.error('[TrueTunes] Failed to load list:', error);
        }
    }

    // Check current track
    function checkCurrentTrack() {
        if (!Spicetify.Player.data) return;
        
        const track = Spicetify.Player.data.track;
        if (!track || !track.metadata) return;
        
        const artistUri = track.metadata.artist_uri;
        if (!artistUri) return;
        
        const artistId = artistUri.split(':').pop();
        const flagged = flaggedArtists.get(artistId);
        
        if (flagged && flagged.confidence >= settings.confidenceThreshold) {
            handleFlaggedTrack(flagged);
        }
    }

    // Handle flagged track
    function handleFlaggedTrack(artist) {
        if (settings.showWarnings) {
            showNotification(artist);
        }
        
        if (settings.autoSkip) {
            setTimeout(() => Spicetify.Player.next(), 500);
        }
        
        if (settings.autoDislike) {
            dislikeTrack();
        }
    }

    // Show notification
    function showNotification(artist) {
        const confidence = Math.round(artist.confidence * 100);
        Spicetify.showNotification(
            `⚠️ AI Generated Music Detected (${confidence}% confidence)`,
            false,
            5000
        );
    }

    // Dislike track
    function dislikeTrack() {
        try {
            const uri = Spicetify.Player.data.track.uri;
            Spicetify.Platform.LibraryAPI.remove({ uris: [uri] });
        } catch (error) {
            console.error('[TrueTunes] Failed to dislike:', error);
        }
    }

    // Vote on current artist
    function voteOnArtist(voteType) {
        const track = Spicetify.Player.data.track;
        const artistName = track.metadata.artist_name;
        const artistId = track.metadata.artist_uri.split(':').pop();
        
        const title = `Vote: ${artistName}`;
        const body = `Platform: Spotify\nArtist ID: ${artistId}\nVote: ${voteType}\n\nAuto-generated by TrueTunes extension`;
        
        const url = `${ISSUE_URL}?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}&labels=vote`;
        
        window.open(url, '_blank');
        Spicetify.showNotification('✓ Vote submitted! Thanks for contributing.', false, 3000);
    }

    // Create settings menu - Disabled for now
    function createSettingsMenu() {
      console.log('[TrueTunes] Menu creation skipped - detection only mode');
    }

    // Initialize
    async function init() {
        if (!Spicetify.Player || !Spicetify.Menu) {
            setTimeout(init, 100);
            return;
        }
        
        console.log('[TrueTunes] Initializing...');
        
        loadSettings();
        await loadFlaggedList();
        
        Spicetify.Player.addEventListener('songchange', checkCurrentTrack);
        
        // createSettingsMenu(); // Disabled for now
        console.log('[TrueTunes] Menu registered (detection only)');
        
        // Auto-refresh every 6 hours
        setInterval(loadFlaggedList, 6 * 60 * 60 * 1000);
        
        console.log('[TrueTunes] Ready!');
    }

    init();
})();